name: "spa-smoke-test-action"
description: "Use this action to run very basic smoke tests for your single-page apps with Puppeteer"
branding:
  icon: "anchor"
  color: "orange"
inputs:
  target-url:
    description: "URL to smoke-test"
    required: true
  target-selector:
    description: "Selector to query"
    required: true
  http-auth-username:
    description: "Username for HTTP Basic Auth"
  http-auth-password:
    description: "Password for HTTP Basic Auth"
  wait-on-start:
    description: "Waiting duration before asserting"
runs:
  using: "node16"
  main: "dist/index.js"
