name: Manual SPA smoke test

on:
  workflow_dispatch:
    inputs:
      target-url:
        description: "URL to smoke-test"
        required: true
        type: string
      target-selector:
        description: "Selector to query"
        required: true
        type: string
      request-url:
        description: "Request to spy (optional)"
        required: false
        type: string
      wait-on-start:
        description: "Waiting duration before asserting (ms, optional)"
        required: false
        default: "0"
        type: string
      engine:
        description: "Browser engine to use (lightpanda, puppeteer, playwright-chrome, playwright-firefox)"
        required: false
        default: "lightpanda"
        type: string

jobs:
  run-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run SPA smoke test
        uses: GabrielCousin/spa-smoke-test-action@v0.3.0
        with:
          target-url: ${{ github.event.inputs["target-url"] }}
          target-selector: ${{ github.event.inputs["target-selector"] }}
          request-url: ${{ github.event.inputs["request-url"] }}
          wait-on-start: ${{ github.event.inputs["wait-on-start"] }}
          engine: ${{ github.event.inputs["engine"] }}
